apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubefirst
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: default
  source:
    repoURL: https://charts.kubefirst.com
    targetRevision: 2.4.10
    chart: kubefirst
    helm:
      values: |-
        global:
          cloudProvider: "aws"
          clusterId: "a4qfpq"
          clusterType: "mgmt"
          domainName: "aws.thecaptainhub.com"
          gitProvider: "github"
          installMethod: "helm"
          kubefirstClient: "<KUBEFIRST_CLIENT>"
          kubefirstTeam: "false"
          kubefirstTeamInfo: ""
          kubefirstVersion: "v2.4.9"
          useTelemetry: ""
        kubefirst-api-ee:
          extraEnv:
            IN_CLUSTER: "true"
        kubefirst-api:
          isClusterZero: "false"
          extraEnv:
            IN_CLUSTER: "true"
            CLUSTER_NAME: "managementcluster"
            ENTERPRISE_API_URL: "http://kubefirst-kubefirst-api-ee.kubefirst.svc.cluster.local"
          serviceAccount:
            create: true
            annotations:
              eks.amazonaws.com/role-arn: arn:aws:iam::637423629731:role/kubefirst-api-managementcluster
        console:
          isClusterZero: "false"
          domain: "aws.thecaptainhub.com"
          extraEnvSecrets:
            CLIENT_ID:
              name: kubefirst-console-secrets
              key: client_id
            SECRET_ID:
              name: kubefirst-console-secrets
              key: client_secret
          ingress:
            enabled: "true"
            className: nginx
            annotations:
              cert-manager.io/cluster-issuer: "letsencrypt-prod"
              
              
              
            hosts:
              - host: kubefirst.aws.thecaptainhub.com
                paths:
                  - path: /
                    pathType: Prefix
            tls:
              - secretName: kubefirst-tls
                hosts:
                  - kubefirst.aws.thecaptainhub.com
  destination:
    name: in-cluster
    namespace: kubefirst
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
