apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: aws-auth
  namespace: external-dns
spec:
  target:
    name: aws-auth
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-kv-secret
  refreshInterval: 10s
  dataFrom:
  - extract:
      key: /external-dns
