metaphor:
  annotations: |
    linkerd.io/inject: "enabled"
  labels: |
    mirror.linkerd.io/exported: "true"
  image:
    repository: ghcr.io/thecaptainhub/metaphor
  imagePullSecrets:
    - name: docker-config
  ingress:
    className: nginx
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: 'letsencrypt-prod'
      nginx.ingress.kubernetes.io/service-upstream: "true"
    hosts:
      - host: metaphor-staging.aws.thecaptainhub.com
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: metaphor-tls
        hosts:
          - metaphor-staging.aws.thecaptainhub.com
  metaphor:
    host: https://metaphor-staging.aws.thecaptainhub.com/api
    console: https://kubefirst.aws.thecaptainhub.com

  clusterSecretStoreName: <WORKLOAD_CLUSTER_NAME>-vault-kv-secret
  vaultSecretPath: <WORKLOAD_CLUSTER_NAME>/metaphor
  configs:
    configOne: <WORKLOAD_CLUSTER_NAME>-config-one
    configTwo: <WORKLOAD_CLUSTER_NAME>-config-two