apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-components
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '50'
spec:
  project: default
  source:
    repoURL: git@github.com:thecaptainhub/gitops.git
    path: registry/clusters/managementcluster/components/argo-workflows
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: argo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 10
      backoff:
        duration: 30s
        maxDuration: 15m0s
        factor: 2
