apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns-components
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '10'
spec:
  project: default
  source:
    repoURL: git@github.com:thecaptainhub/gitops.git
    path: registry/clusters/managementcluster/components/external-dns
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: external-dns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
