apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: staging-cert-issuers
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: '40'
spec:
  project: staging
  source:
    repoURL: git@github.com:thecaptainhub/gitops.git
    path: registry/clusters/staging/cert-issuers
    targetRevision: HEAD
  destination:
    name: staging
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
