apiVersion: tf.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: staging
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  configuration: |
      terraform {
        backend "s3" {
          bucket   = "k1-state-store-managementcluster-a4qfpq"
          key      = "registry/clusters/staging/infrastructure/provider-config/terraform.tfstate"
          region = "ap-south-1"
        }
        required_providers {
          kubernetes = {
            source = "hashicorp/kubernetes"
            version = "2.23.0"
          }
          vault = {
            source = "hashicorp/vault"
            version = "3.19.0"
          }
        }
      }
  credentials:
  - filename: gen-nothing
    source: None
    secretRef:
      namespace: crossplane-system
      name: civo-creds
      key: token
  - filename: .git-credentials
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: git-credentials
      key: creds
